name: my-next-film-list

services:
  # This config is for MongoDB v8
  # It's a Replica Set (required for Prisma Client)
  mongodb-replicaset:
    build:
      context: ./
      args:
        MONGO_VERSION: 8.0
    container_name: mongodb-replicaset
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    # restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "admin", "--port", "27019", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 2s
      retries: 20
